version: '3.4'

services:
  redis:
    image: redis:latest
    ports:
      - '6379:6379'
    volumes:
      - 'redis_data:/data'

  message-logger:
    image: message-logger
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on:
      - redis
    environment:
      NODE_ENV: production
      REDIS_HOST: redis
    ports:
      - 8080:8080

volumes:
  redis_data:
    driver: local
